"""Describe your change here

Revision ID: 351954d66b10
Revises: 2f3dea854f87
Create Date: 2024-09-09 19:47:32.777671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351954d66b10'
down_revision = '2f3dea854f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
